language: ruby
rvm:
  - 2.3.3
before_install:
  - nvm install 6.10.2
  - nvm use 6.10.2
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - cd client && npm install
script:
  - bundle exec rake
  - cd client && npm run ci-test
